# frozen_string_literal: true
# Proc#arity
p(->(a, b) { a + b }.arity)
v001 = ->(a, b) { a + b }.arity; p(v001)
a001 = ->(a, b) { a + b }; p(a001.arity)
v002 = a001.arity; p(v002)
p(proc { |x| x * x }.arity)
v003 = proc { |x| x * x }.arity; p(v003)
p(->(a, b = 1) {}.arity)
v010 = ->(a, b = 1) {}.arity; p(v010)
p(->(a, *r) {}.arity)
v011 = ->(a, *r) {}.arity; p(v011)
p(->(*r) {}.arity)
p(->() {}.arity)
p(->(a, k:) {}.arity)
v012 = ->(a, k:) {}.arity; p(v012)
p(->(a, k: 2) {}.arity)
pa618 = [->(x618) { x618 }]; a618 = (pa618.map(&:arity) rescue $!.class); p a618
# every lambda shape
p(->() {}.arity)
v020 = ->() {}.arity; p(v020)
p(->(a) {}.arity)
v021 = ->(a) {}.arity; p(v021)
p(->(a, b = 1) {}.arity)
p(->(*a) {}.arity)
v022 = ->(*a) {}.arity; p(v022)
p(->(a, *b) {}.arity)
v023 = ->(a, *b) {}.arity; p(v023)
p(->(a:, b: 1) {}.arity)
v024 = ->(a:, b: 1) {}.arity; p(v024)
p(->(**kw) {}.arity)
v025 = ->(**kw) {}.arity; p(v025)
p(->(&blk) {}.arity)
v026 = ->(&blk) {}.arity; p(v026)
p(->(a, b = 1, *c, d:, e: 2, **f, &g) {}.arity)
v027 = ->(a, b = 1, *c, d:, e: 2, **f, &g) {}.arity; p(v027)
p(->((a, b)) {}.arity)
# every proc (non-lambda) shape
p(proc {}.arity)
v030 = proc {}.arity; p(v030)
p(proc { |a| }.arity)
p(proc { |a, b = 1| }.arity)
v031 = proc { |a, b = 1| }.arity; p(v031)
p(proc { |*a| }.arity)
p(proc { |a, *b| }.arity)
v032 = proc { |a, *b| }.arity; p(v032)
p(proc { |a:, b: 1| }.arity)
p(proc { |&blk| }.arity)
v033 = proc { |&blk| }.arity; p(v033)
p(proc { |(a, b)| }.arity)
p(proc { |**kw| }.arity)
v034 = proc { |**kw| }.arity; p(v034)
p(proc { |a, **kw| }.arity)
# arity of a composed, curried and Symbol-derived proc
p((->(a, b) { a + b } >> ->(x) { x }).arity)
v035 = (->(a, b) { a + b } >> ->(x) { x }).arity; p(v035)
p(->(a, b, c) { a }.curry.arity)
v036 = ->(a, b, c) { a }.curry.arity; p(v036)
p(->(a, b, c) { a }.curry[1].arity)
p(:upcase.to_proc.arity)
p(2.method(:*).to_proc.arity)
v037 = 2.method(:*).to_proc.arity; p(v037)
